### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/quasar-app-extension-quasar-select-options-tree: Not found"

### ISSUE THREAD

**Issue by kcker** [Nikitoring/quasar-qselect-option-tree#1]
quasar ext add quasar-select-options-tree
=>
An unexpected error occurred: "https://registry.yarnpkg.com/quasar-app-extension-quasar-select-options-tree: Not found"

**Comment by Nikitoring** [comment]
Yes, I will solve this problem soon  and i'm going to  update extension without q-tree component

**Comment by Nikitoring** [comment]
@kcker I Update my extension. please check
